'use server';

import { ai } from '@/ai/genkit';
import { googleAI } from '@genkit-ai/googleai';
import { z } from 'genkit';
import { voiceOptions, type VoiceOption } from '@/lib/types';

const GenerateVoiceoverInputSchema = z.object({
  text: z.string().describe('The text to be converted to speech.'),
  voice: z.enum(voiceOptions).describe('The voice to use for the speech synthesis.'),
  languageCode: z.string().describe('The BCP-47 language code for the speech synthesis (e.g., "en-US", "es-ES").'),
});
export type GenerateVoiceoverInput = z.infer<typeof GenerateVoiceoverInputSchema>;

const GenerateVoiceoverOutputSchema = z.object({
  audioUrl: z.string().describe('The generated audio as a data URI. Expected format: \'data:audio/wav;base64,<encoded_data>\''),
});
export type GenerateVoiceoverOutput = z.infer<typeof GenerateVoiceoverOutputSchema>;

export async function generateVoiceover(input: GenerateVoiceoverInput): Promise<GenerateVoiceoverOutput> {
  return generateVoiceoverFlow(input);
}

const generateVoiceoverFlow = ai.defineFlow(
  {
    name: 'generateVoiceoverFlow',
    inputSchema: GenerateVoiceoverInputSchema,
    outputSchema: GenerateVoiceoverOutputSchema,
  },
  async ({ text, voice, languageCode }) => {
    try {
      const resp = await ai.generate({
        model: googleAI.model('gemini-2.5-flash-exp'),
        prompt: text,
        config: {
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: voice },
            },
            languageCode: languageCode,
          },
        },
      });

      const media = Array.isArray((resp as any).media) ? (resp as any).media : [(resp as any).media];
      const audioUrl = media?.[0]?.url;

      if (!audioUrl) {
        throw new Error('No audio was generated by the TTS model.');
      }

      return { audioUrl };
      
    } catch (error: any) {
      if (error.message?.includes('billing')) {
        throw new Error('Voice generation requires billing to be enabled on your Google Cloud account.');
      }
      throw new Error(`Failed to generate voiceover: ${error.message}`);
    }
  }
);