'use server';

import { z } from 'zod';
import { ai } from '@/ai/genkit';
import { googleAI } from '@genkit-ai/googleai';
import { translateText } from './translate-text';

const GenerateVoiceoverInputSchema = z.object({
  text: z.string().min(1).max(4000).describe('The text to be converted to speech.'),
  voice: z.string().describe('Voice name (Algenib, Antares, Arcturus, etc.)'),
  languageCode: z.string().default('en-US').describe('BCP-47 language code'),
  autoTranslate: z.boolean().default(true).describe('Automatically translate text to target language'),
});
export type GenerateVoiceoverInput = z.infer<typeof GenerateVoiceoverInputSchema>;

const GenerateVoiceoverOutputSchema = z.object({
  audioUrl: z.string().describe('Base64 encoded audio data URL'),
  mimeType: z.string().describe('Audio format').optional(),
  duration: z.number().optional(),
  translatedText: z.string().optional().describe('The text that was converted to speech (may be translated)'),
});
export type GenerateVoiceoverOutput = z.infer<typeof GenerateVoiceoverOutputSchema>;

export async function generateVoiceover(input: GenerateVoiceoverInput): Promise<GenerateVoiceoverOutput> {
  return generateVoiceoverFlow(input);
}

function pcmToWavBase64(pcmBase64: string, sampleRate = 24000, numChannels = 1, bitsPerSample = 16): string {
  const pcmBuffer = Buffer.from(pcmBase64, 'base64');
  const dataLength = pcmBuffer.length;
  
  // Wave header size is 44 bytes
  const wavBuffer = Buffer.alloc(44 + dataLength);
  
  // "RIFF" chunk descriptor
  wavBuffer.write('RIFF', 0);
  wavBuffer.writeUInt32LE(36 + dataLength, 4); // Chunk size
  wavBuffer.write('WAVE', 8);

  // "fmt " sub-chunk
  wavBuffer.write('fmt ', 12);
  wavBuffer.writeUInt32LE(16, 16); // Subchunk1Size (16 for PCM)
  wavBuffer.writeUInt16LE(1, 20); // AudioFormat (1 for PCM)
  wavBuffer.writeUInt16LE(numChannels, 22); // NumChannels
  wavBuffer.writeUInt32LE(sampleRate, 24); // SampleRate
  
  const byteRate = sampleRate * numChannels * (bitsPerSample / 8);
  wavBuffer.writeUInt32LE(byteRate, 28); // ByteRate
  
  const blockAlign = numChannels * (bitsPerSample / 8);
  wavBuffer.writeUInt16LE(blockAlign, 32); // BlockAlign
  wavBuffer.writeUInt16LE(bitsPerSample, 34); // BitsPerSample
  
  // "data" sub-chunk
  wavBuffer.write('data', 36);
  wavBuffer.writeUInt32LE(dataLength, 40); // Subchunk2Size
  
  // Write PCM data
  pcmBuffer.copy(wavBuffer, 44);
  
  return wavBuffer.toString('base64');
}

const generateVoiceoverFlow = ai.defineFlow(
  {
    name: 'generateVoiceoverFlow',
    inputSchema: GenerateVoiceoverInputSchema,
    outputSchema: GenerateVoiceoverOutputSchema,
  },
  async ({ text, voice, languageCode, autoTranslate }) => {
    try {
      let textToSpeak = text;
      
      // Force autoTranslate to true if not explicitly set to false
      const shouldTranslate = autoTranslate !== false;

      // Translate text if language is not English and autoTranslate is enabled
      if (shouldTranslate && languageCode !== 'en-US') {
        console.log(`Translating text to ${languageCode}...`);
        try {
          const translation = await translateText({
            text: text,
            targetLanguage: languageCode,
          });
          textToSpeak = translation.translatedText;
          console.log(`Translated: ${textToSpeak.substring(0, 100)}...`);
        } catch (translationError: any) {
          console.error('Translation failed, using original text:', translationError.message);
          // Continue with original text if translation fails
        }
      }

      console.log(`Generating native Gemini TTS: Voice (${voice})`);
      const resp = await ai.generate({
        model: 'googleai/gemini-2.5-flash-preview-tts', // Officially supported API endpoint for preview Text-To-Speech
        prompt: `Dictate the following text out loud strictly and accurately without generating any text output: ${textToSpeak}`,
        config: {
          responseModalities: ['AUDIO'],
          speechConfig: {
            voiceConfig: {
              prebuiltVoiceConfig: { voiceName: voice },
            },
            languageCode: languageCode,
          },
        },
      });

      // Extract media directly from the Genkit 1.14 message.content array
      const contentParts = resp.message?.content || [];
      const mediaPart = contentParts.find((part: any) => part.media && typeof part.media.url === 'string');
      const audioUrlInfo = mediaPart?.media?.url;

      if (!audioUrlInfo || !audioUrlInfo.startsWith('data:audio/')) {
        throw new Error('No valid audio data URI was generated by the native Gemini TTS model. Check quota and model availability.');
      }

      const commaIndex = audioUrlInfo.indexOf(',');
      const rawBase64 = audioUrlInfo.substring(commaIndex + 1);
      const wavBase64 = pcmToWavBase64(rawBase64);
      const outputAudioUrl = `data:audio/wav;base64,${wavBase64}`;

      const wordCount = textToSpeak.split(/\s+/).length;
      const estimatedDuration = Math.ceil(wordCount / 2.5);

      return {
        audioUrl: outputAudioUrl,
        mimeType: 'audio/wav',
        duration: estimatedDuration,
        translatedText: textToSpeak,
      };
      
    } catch (error: any) {
      if (error.message?.includes('billing')) {
        throw new Error('Voice generation requires billing to be enabled on your Google Cloud account.');
      }
      if (error.message?.includes('429') || error.message?.includes('quota')) {
        throw new Error('AI quota exceeded. Please try again later or check billing.');
      }
      throw new Error(`Failed to generate voiceover natively via Gemini API: ${error.message}`);
    }
  }
);