'use server';

import { ai } from '@/ai/genkit';
import { googleAI } from '@genkit-ai/googleai';
import { z } from 'genkit';
import { Scene, TrailerConfig } from '@/lib/types';

const GenerateTrailerInputSchema = z.object({
  scenes: z.array(z.any()).describe('An array of scene objects, including image URLs and narration.'),
  config: z.any().describe('The configuration for the trailer generation.'),
});
export type GenerateTrailerInput = z.infer<typeof GenerateTrailerInputSchema>;

const GenerateTrailerOutputSchema = z.object({
  videoUrl: z.string().describe('The URL of the generated trailer video.'),
});
export type GenerateTrailerOutput = z.infer<typeof GenerateTrailerOutputSchema>;

export async function generateTrailer(input: GenerateTrailerInput): Promise<GenerateTrailerOutput> {
  return generateTrailerFlow(input);
}

async function imageUrlToDataUri(url: string): Promise<string> {
  try {
    const response = await fetch(url);
    if (!response.ok) {
      console.warn(`Failed to fetch image ${url}. Status: ${response.status}`);
      return url;
    }
    const contentType = response.headers.get('content-type') || 'image/png';
    const buffer = await response.arrayBuffer();
    const base64 = Buffer.from(buffer).toString('base64');
    return `data:${contentType};base64,${base64}`;
  } catch (error) {
    console.warn(`Error fetching image ${url}:`, error);
    return url;
  }
}

const generateTrailerFlow = ai.defineFlow(
  {
    name: 'generateTrailerFlow',
    inputSchema: GenerateTrailerInputSchema,
    outputSchema: GenerateTrailerOutputSchema,
  },
  async ({ scenes, config }) => {
    const imageScenes = scenes.filter((s: any) => s.imageUrl);

    if (imageScenes.length === 0) {
      throw new Error("Cannot generate a trailer without at least one scene with a visual.");
    }

    try {
      const imageDataUris = await Promise.all(
        imageScenes.map((s: any) => imageUrlToDataUri(s.imageUrl))
      );

      const prompt = `Create a cinematic trailer video with a duration of ${config.length} seconds.
          The overall tone should be ${config.tone}.
          Use the following scenes in sequence.
          Generate appropriate transitions between scenes to match the tone.
          ${config.includeMusic ? `Incorporate ${config.musicGenre.toLowerCase()} background music.` : ''}
          ${config.includeTextOverlays ? 'Include text overlays for scene titles or key narration moments.' : ''}`;

      const generationPrompt: any[] = [prompt];
      imageDataUris.forEach(dataUri => {
        generationPrompt.push({
          media: { 
            url: dataUri, 
            contentType: 'image/jpeg' 
          }
        });
      });

      const resp = await ai.generate({
        model: googleAI.model('gemini-3-pro-preview'),
        prompt: generationPrompt,
        config: {
          durationSeconds: parseInt(config.length, 10),
          aspectRatio: '16:9',
        },
      });

      const media = Array.isArray((resp as any).media) ? (resp as any).media : [(resp as any).media];
      const videoUrl = media?.[0]?.url;

      if (!videoUrl) {
        throw new Error('No video was generated by the model.');
      }

      const videoDataUri = await imageUrlToDataUri(videoUrl);
      return { videoUrl: videoDataUri };
      
    } catch (error: any) {
      if (error.message?.includes('billing')) {
        throw new Error('Video generation requires a Google Cloud Platform account with billing enabled.');
      }
      throw new Error(`Failed to generate trailer: ${error.message}`);
    }
  }
);